export const SIGN_AUTH_TOKENS = "SIGN_AUTH_TOKENS";
export const TOKEN_CREATE = "TOKEN_CREATE";
export const TOKEN_DECODE = "TOKEN_DECODE";
export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const SEND_EMAIL = "SEND_EMAIL";
export const PRESIGNED_CREATE = "PRESIGNED_CREATE";
export const PRESIGNED_CREATE_POST = "PRESIGNED_CREATE_POST";
export const GET_USERS_BY_IDS = "GET_USERS_BY_IDS";
